In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os, math

In [11]:
df = pd.read_csv("secondhand_car.csv", sep=";")
df.head()

,Car ID,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
0,0,Toyota,Vitz,2385000.0,2017.0,Islamabad,9869.0,Petrol,1000.0,Silver,Imported,Hatchback,Automatic,Un-Registered
1,1,Toyota,Corolla,111000.0,2019.0,KPK,11111.0,Petrol,1300.0,White,Local,Sedan,Automatic,Registered
2,2,Suzuki,Alto,1530000.0,2019.0,KPK,17500.0,Petrol,660.0,White,Local,Hatchback,Automatic,Un-Registered
3,3,Suzuki,Alto,1650000.0,2019.0,Punjab,9600.0,Petrol,660.0,White,Local,Hatchback,Manual,Registered
4,4,Toyota,Corolla,1435000.0,2010.0,Islamabad,120000.0,Petrol,1300.0,Black,Local,Sedan,Manual,Registered

In [12]:
df = df.drop('Car ID', axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46022 entries, 0 to 46021
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company Name         46010 non-null  object
 1   Model Name           45980 non-null  object
 2   Price                45931 non-null  float64
 3   Model Year           45935 non-null  float64
 4   Location             45948 non-null  object
 5   Mileage              45976 non-null  float64
 6   Engine Type          45977 non-null  object
 7   Engine Capacity      45978 non-null  float64
 8   Color                45976 non-null  object
 9   Assembly             45948 non-null  object
 10  Body Type            45958 non-null  object
 11  Transmission Type    45966 non-null  object
 12  Registration Status  45989 non-null  object
dtypes: float64(4), object(9)
memory usage: 4.6+ MB

In [13]:
df.isna().sum()

Company Name           12
Model Name             42
Price                  91
Model Year             87
Location               74
Mileage                46
Engine Type            45
Engine Capacity        44
Color                  46
Assembly               74
Body Type              64
Transmission Type      56
Registration Status    33
dtype: int64

In [14]:
df.nunique()

Company Name             31
Model Name              196
Price                  1417
Model Year               30
Location                  6
Mileage                5568
Engine Type               3
Engine Capacity          75
Color                    24
Assembly                  2
Body Type                 6
Transmission Type         2
Registration Status       2
dtype: int64

In [15]:
df[df.duplicated()]

,Company Name,Model Name,Price,Model Year,Location,Mileage,Engine Type,Engine Capacity,Color,Assembly,Body Type,Transmission Type,Registration Status
600,Daihatsu,Mira,1345000.0,2014.0,Sindh,77000.0,Petrol,660.0,Beige,Imported,Hatchback,Automatic,Registered
1319,Suzuki,Swift,1450000.0,2013.0,Sindh,81939.0,Petrol,1300.0,Silver,Local,Hatchback,Automatic,Registered
1684,Honda,City,2065000.0,2017.0,Punjab,52000.0,Petrol,1300.0,Black,Local,Sedan,Manual,Registered
1813,Suzuki,Wagon,1300000.0,2011.0,Punjab,150000.0,Petrol,660.0,Black,Imported,Hatchback,Automatic,Registered
1896,Toyota,Corolla,2100000.0,2016.0,Punjab,92000.0,Petrol,1300.0,Grey,Local,Sedan,Manual,Registered
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45835,Suzuki,Mehran,450000.0,2007.0,Punjab,75000.0,Petrol,800.0,Blue,Local,Hatchback,Manual,Registered
45846,Suzuki,Cultus,540000.0,2006.0,Sindh,126000.0,Petrol,1000.0,Black,Local,Hatchback,Manual,Registered
45889,Suzuki,Wagon,1550000.0,2018.0,Punjab,38000.0,Petrol,1000.0,White,Local,Hatchback,Manual,Registered
45993,Toyota,Corolla,1680000.0,2012.0,Sindh,28000.0,Petrol,1300.0,White,Local,Sedan,Manual,Registered
46006,Daihatsu,Mira,1800000.0,2016.0,Sindh,23000.0,Petrol,660.0,White,Imported,Hatchback,Automatic,Un-Registered